[build]
  publish = "."

  # Install dependencies and build command
  command = "pip install -r requirements.txt"

[functions]
  # Point to where your FastAPI app will be deployed as serverless functions
  directory = "netlify/functions"
